name: CI/CD to EC2

on:
  push:
    branches: [ main ]  # trigger deployment on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.117.133.97 "\
          cd /home/ubuntu/PixelMorph/pixelMorphBackend && \
          git reset --hard && git pull origin main && \
          source venv/bin/activate && \
          pip install -r requirements.txt && \
          pkill -f 'uvicorn main:app' || true && \
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 & disown \
          "


